import type { Metadata } from 'next';
import './globals.css';
import Navbar from './_components/Nav';
import Footer from './_components/Footer.tsx';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-background overflow-x-clip bg-ellipses bg-right-top bg-contain bg-no-repeat w-screen"
        style={{ backgroundSize: '42%' }}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
