import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Navbar from './_components/Nav';
import Footer from './_components/Footer.tsx';
import Image from 'next/image';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-background overflow-x-clip bg-ellipses bg-right-top bg-contain bg-no-repeat w-screen"
        style={{ backgroundSize: '42%' }}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
